language: python
python: "3.6"
sudo: false # only for faster builds

install:
  - pip install requests

script: 
  - chmod +x src/download_stats.py
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/begarco/stats.git > /dev/null 2>&1
  - BEGIN=`ls -la data | wc -l`
  - python src/download_stats.py $GITHUB_TOKEN
  - echo "projects-"`date +%Y-%m-%d`".json" > data/latest
  - python src/history.py
  - END=`ls -la data | wc -l`
  - ls -la data
  - echo "$BEGIN and $END"
  - if [ $BEGIN -ne $END ]; then git add data/*; fi
  - if [ $BEGIN -ne $END ]; then git commit -m "[BUILD $TRAVIS_BUILD_NUMBER] Commitment of new data"; fi
  - if [ $BEGIN -ne $END ]; then git push origin HEAD:master; fi
